In [1]:
import pandas as pd

In [2]:
s = pd.Series([1,2,3,4,5],name ="marks")

In [3]:
print(type(s))

<class 'pandas.Series'>

In [4]:
print(s)

0    1
1    2
2    3
3    4
4    5
Name: marks, dtype: int64

In [5]:
print(s.mean())

3.0

**DataFrame**

In [6]:
data = {
    "Name":["Alice",'Bob',"Charlie","David"],
    "Age":[24,27,22,32],
    "Score": [85,71,78,91]
}
print(type(data))
print(data)

<class 'dict'>
{'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [24, 27, 22, 32], 'Score': [85, 71, 78, 91]}

In [7]:
df = pd.DataFrame(data)

In [8]:
print(type(df))
print(df)

<class 'pandas.DataFrame'>
      Name  Age  Score
0    Alice   24     85
1      Bob   27     71
2  Charlie   22     78
3    David   32     91

In [9]:
print(df.head())
print("----------------------")
print(df.tail())

      Name  Age  Score
0    Alice   24     85
1      Bob   27     71
2  Charlie   22     78
3    David   32     91
----------------------
      Name  Age  Score
0    Alice   24     85
1      Bob   27     71
2  Charlie   22     78
3    David   32     91

In [10]:
df.to_csv("sample.csv",index= False)

**Read data from a CSV file**

In [11]:
df1 = pd.read_csv("sample.csv")

print(df1)

      Name  Age  Score
0    Alice   24     85
1      Bob   27     71
2  Charlie   22     78
3    David   32     91

In [12]:
df1.shape

(4, 3)

In [13]:
df1.columns

Index(['Name', 'Age', 'Score'], dtype='str')

In [14]:
df.head()

      Name  Age  Score
0    Alice   24     85
1      Bob   27     71
2  Charlie   22     78
3    David   32     91

In [15]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Score   4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

**Inspecting the Data**

In [16]:
print(df1.shape)
print(df1.columns)
print(df1.dtypes)

(4, 3)
Index(['Name', 'Age', 'Score'], dtype='str')
Name       str
Age      int64
Score    int64
dtype: object

In [17]:
#single column
print(type(df1["Name"]))
print(df1["Name"])

<class 'pandas.Series'>
0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str

In [18]:
#multiple columns
print(df[["Name","Age"]])

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
3    David   32

In [19]:
#row selection:
print(df.iloc[1]) #by index

Name     Bob
Age       27
Score     71
Name: 1, dtype: object

In [20]:
print(df.loc[0])   #by label

Name     Alice
Age         24
Score       85
Name: 0, dtype: object

In [21]:
data = {
    "Name": ['Anna','Ben','Cara','Dana'],
    'Score':[81,82,59,70]
}

In [22]:
df2 = pd.DataFrame(data, index=['a','b','c','d'])

In [23]:
df2.head()

   Name  Score
a  Anna     81
b   Ben     82
c  Cara     59
d  Dana     70

In [24]:
df2.iloc[1]

Name     Ben
Score     82
Name: b, dtype: object

In [25]:
df2.loc['b']

Name     Ben
Score     82
Name: b, dtype: object

**Filtering Data**

In [26]:
df

      Name  Age  Score
0    Alice   24     85
1      Bob   27     71
2  Charlie   22     78
3    David   32     91

In [27]:
high_scores = df[df['Score']>84]
print(high_scores)

    Name  Age  Score
0  Alice   24     85
3  David   32     91

**Adding new column**

In [28]:
df["Passed"] = df["Score"] >84
print(df)

      Name  Age  Score  Passed
0    Alice   24     85    True
1      Bob   27     71   False
2  Charlie   22     78   False
3    David   32     91    True

In [29]:
df["Score_Percentage"] = df["Score"] / 100*100

In [30]:
df

      Name  Age  Score  Passed  Score_Percentage
0    Alice   24     85    True              85.0
1      Bob   27     71   False              71.0
2  Charlie   22     78   False              78.0
3    David   32     91    True              91.0

In [31]:
df["city"] = ["Pune","Mumbai","Lucknow","Jaipur"]

In [32]:
df

      Name  Age  Score  Passed  Score_Percentage     city
0    Alice   24     85    True              85.0     Pune
1      Bob   27     71   False              71.0   Mumbai
2  Charlie   22     78   False              78.0  Lucknow
3    David   32     91    True              91.0   Jaipur

**Descriptive Statistics**

In [33]:
print(df["Score"].mean())
print(df["Score"].max())
print(df["Score"].min())

81.25
91
71

In [34]:
df.describe()

             Age      Score  Score_Percentage
count   4.000000   4.000000          4.000000
mean   26.250000  81.250000         81.250000
std     4.349329   8.655441          8.655441
min    22.000000  71.000000         71.000000
25%    23.500000  76.250000         76.250000
50%    25.500000  81.500000         81.500000
75%    28.250000  86.500000         86.500000
max    32.000000  91.000000         91.000000

**Handling missing data**

In [35]:
df2 = pd.DataFrame(
    {
    "Name":["Alice",None,"Charlie","David"],
    "Age":[24,27,22,None],
    "Score": [None,71,78,91]
    }
)

In [36]:
df2.dropna(subset=["Name"], inplace=True)

In [37]:
df2.head()

      Name   Age  Score
0    Alice  24.0    NaN
2  Charlie  22.0   78.0
3    David   NaN   91.0

In [38]:
df2['Age'] = df2['Age'].fillna(df2['Age'].mean())
df2['Score'] = df2['Score'].fillna(df2['Score'].mean())

In [39]:
df2

      Name   Age  Score
0    Alice  24.0   84.5
2  Charlie  22.0   78.0
3    David  23.0   91.0

**Sorting**

In [40]:
df2.sort_values(by="Score", ascending=False)

      Name   Age  Score
3    David  23.0   91.0
0    Alice  24.0   84.5
2  Charlie  22.0   78.0

**Filtering using multiple conditions:**

In [41]:
df

      Name  Age  Score  Passed  Score_Percentage     city
0    Alice   24     85    True              85.0     Pune
1      Bob   27     71   False              71.0   Mumbai
2  Charlie   22     78   False              78.0  Lucknow
3    David   32     91    True              91.0   Jaipur

In [42]:
df[(df["Score"] > 80) & (df["Age"] > 22)]

    Name  Age  Score  Passed  Score_Percentage    city
0  Alice   24     85    True              85.0    Pune
3  David   32     91    True              91.0  Jaipur